CXX = g++
CXXFLAGS =

TEMPLATES_PATH = templates
HEADERS_PATH = include
OBJECTS_PATH = objects
TESTS_PATH = tests

NodeTest:
	$(CXX) $(CXXFLAGS) $(TESTS_PATH)/NodeTest.cpp -I $(TEMPLATES_PATH)/ -I $(HEADERS_PATH)/

GraphInsertionTest:
	$(CXX) $(CXXFLAGS) $(TESTS_PATH)/GraphInsertionTest.cpp -I $(TEMPLATES_PATH)/ -I $(HEADERS_PATH)/

GraphSetEdgeTest:
	$(CXX) $(CXXFLAGS) $(TESTS_PATH)/GraphSetEdgeTest.cpp -I $(TEMPLATES_PATH)/ -I $(HEADERS_PATH)/

UtilTest:
	$(CXX) $(CXXFLAGS) $(TESTS_PATH)/UtilTest.cpp -I $(TEMPLATES_PATH)/ -I $(HEADERS_PATH)/

RemoveTest:
	$(CXX) $(CXXFLAGS) $(TESTS_PATH)/RemoveTest.cpp -I $(TEMPLATES_PATH)/ -I $(HEADERS_PATH)/

NodeIteratorTest:
	$(CXX) $(CXXFLAGS) $(TESTS_PATH)/NodeIteratorTest.cpp -I $(TEMPLATES_PATH)/ -I $(HEADERS_PATH)/

AllEdgesIteratorTest:
	$(CXX) $(CXXFLAGS) $(TESTS_PATH)/AllEdgesIteratorTest.cpp -I $(TEMPLATES_PATH)/ -I $(HEADERS_PATH)/